import type { Post } from "../src/lib/content/posts";
import { extractCodeLanguageUsages, resolveCodeLanguages } from "../src/lib/content/code-languages";
import { bundledLanguagesInfo } from "shiki/langs";

export function collectShikiLanguages(posts: readonly Post[]) {
	const languages = new Set<string>();
	const aliases = new Map<string, string>();

	for (const post of posts) {
		const resolved = resolveCodeLanguages(
			extractCodeLanguageUsages(post.content),
			bundledLanguagesInfo,
			post.sourcePath,
		);
		for (const language of resolved.languages) languages.add(language);
		for (const [alias, canonical] of Object.entries(resolved.aliases)) aliases.set(alias, canonical);
	}

	return {
		aliases: Object.fromEntries([...aliases].sort(([left], [right]) => left.localeCompare(right))),
		languages: [...languages].sort(),
	};
}

export function renderShikiLanguageRegistry(posts: readonly Post[]) {
	const { aliases, languages } = collectShikiLanguages(posts);
	const imports = [
		...languages.map((language) => [language, language] as const),
		...Object.entries(aliases).map(([alias, canonical]) => [alias, canonical] as const),
	]
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([name, canonical]) => `\t${JSON.stringify(name)}: () => import(${JSON.stringify(`@shikijs/langs/${canonical}`)}),`);

	return [
		"// Generated by scripts/generate-shiki-languages.ts. Do not edit manually.",
		'import type { LanguageInput } from "shiki/core";',
		"",
		"export const productionLanguages = {",
		...imports,
		"} satisfies Record<string, LanguageInput>;",
		"",
	].join("\n");
}
